Repository cse110-fa21-group2/cse110-fa21-group2, pull requests merged in 2021-11, with the labels that each got.

#19 Create recipePage.html
  source/recipePage.html
Labels: todo pre-alpha

#26 set up basic eslint/stylelint rules
  .eslintrc.js
  .gitignore
  .stylelintrc.js
  package-lock.json
  package.json
  source/home.html
  source/page-templates/explore.css
  source/page-templates/landing.css
  source/page-templates/search-results.css
  source/styles/home.css
Labels: pipeline, lint

#39 bug fixed, linter now runs properly
  .eslintrc.js
  package.json
Labels: bug

#41 Week7 api helper functions
  .gitignore
  source/scripts/apiHelpers.mjs
Labels: todo pre-alpha

#43 Meeting minutes
  admin/meetings/internal/11_14_21_notes.md
  source/scripts/expanded_recipe_card.js
  source/scripts/recipe_pages.js
  source/scripts/recipe_pages_router.js
Labels: documentation

#52 Week7 githubactions2
  .github/workflows/main.yml
  __tests__/e2e_tests.test.js
  __tests__/unit_tests.test.js
  __tests__/unit_tests_hard.test.js
  package-lock.json
  package.json
Labels: todo pre-alpha, pipeline

#56 #29 - saved recipe page
  source/components/RecipeCard.js
  source/demo-code/bootstrap-navbar/bootstrap_navbar_example.html
  source/demo-code/home-rough/home.css
  source/demo-code/home-rough/home.html
  source/demo-code/integrated-frontend/explore.css
  source/demo-code/integrated-frontend/explore.html
  source/demo-code/integrated-frontend/landing.css
  source/demo-code/integrated-frontend/landing.html
  source/demo-code/integrated-frontend/saved-recipes.css
  source/demo-code/integrated-frontend/saved-recipes.html
  source/demo-code/integrated-frontend/search-results.css
  source/demo-code/integrated-frontend/search-results.html
  source/demo-code/recipe-info-rough/recipePage.html
  source/demo-code/web-component-page/recipe.js
  source/demo-code/web-component-page/recipecard.html
  source/page-templates/explore.html
  source/page-templates/landing.css
  source/page-templates/search-results.css
  source/page-templates/search-results.html
  source/savedRecipePage.html
  source/styles/page-layout.css
  source/styles/recipe-card.css
Labels: todo pre-alpha

#58 Week8 add api helper functions
  .gitignore
  package-lock.json
  package.json
  source/scripts/apiHelpers.js
  source/scripts/apiHelpers.mjs
Labels: todo pre-alpha

#65 Week8 recipe page jon&antonia
  .DS_Store
  source/.DS_Store
  source/demo-code/.DS_Store
  source/demo-code/recipe-info-rough/.DS_Store
  source/demo-code/recipe-info-rough/0-star.svg
  source/demo-code/recipe-info-rough/1-star.svg
  source/demo-code/recipe-info-rough/2-star.svg
  source/demo-code/recipe-info-rough/3-star.svg
  source/demo-code/recipe-info-rough/4-star.svg
  source/demo-code/recipe-info-rough/5-star.svg
  source/demo-code/recipe-info-rough/image.webp
  source/demo-code/recipe-info-rough/recipe-page.css
  source/demo-code/recipe-info-rough/recipePage.html
Labels: help wanted, todo pre-alpha

#104 76 navbar responsiveness
  package-lock.json
  package.json
  source/demo-code/recipe-info-rough/recipe-page.css
  source/demo-code/recipe-info-rough/recipePage.html
  source/demo-code/recipe-info-rough/recipePage.js
Labels: 3 points
