Repository cse110-fa21-group2/cse110-fa21-group2, pull requests merged in 2021-12, with the labels that each got.

#151 Added JSDocs and modified package.json to have the linter ignore the …
  out/Router.js.html
  out/apiHelpers.js.html
  out/fonts/OpenSans-Bold-webfont.eot
  out/fonts/OpenSans-Bold-webfont.svg
  out/fonts/OpenSans-Bold-webfont.woff
  out/fonts/OpenSans-BoldItalic-webfont.eot
  out/fonts/OpenSans-BoldItalic-webfont.svg
  out/fonts/OpenSans-BoldItalic-webfont.woff
  out/fonts/OpenSans-Italic-webfont.eot
  out/fonts/OpenSans-Italic-webfont.svg
  out/fonts/OpenSans-Italic-webfont.woff
  out/fonts/OpenSans-Light-webfont.eot
  out/fonts/OpenSans-Light-webfont.svg
  out/fonts/OpenSans-Light-webfont.woff
  out/fonts/OpenSans-LightItalic-webfont.eot
  out/fonts/OpenSans-LightItalic-webfont.svg
  out/fonts/OpenSans-LightItalic-webfont.woff
  out/fonts/OpenSans-Regular-webfont.eot
  out/fonts/OpenSans-Regular-webfont.svg
  out/fonts/OpenSans-Regular-webfont.woff
  out/global.html
  out/index.html
  out/main.js.html
  out/scripts/linenumber.js
  out/scripts/prettify/Apache-License-2.0.txt
  out/scripts/prettify/lang-css.js
  out/scripts/prettify/prettify.js
  out/styles/jsdoc-default.css
  out/styles/prettify-jsdoc.css
  out/styles/prettify-tomorrow.css
  package-lock.json
  package.json
Labels: documentation, house-keeping

#162 133 populate from api
  source/index.html
  source/js/main.js
Labels: high priority

#164 158 fix base serving size
  package-lock.json
  package.json
  source/js/main.js
Labels: 1 point

#178 add 3 adr
  specs/adrs/141121-API.md
  specs/adrs/211121-timer.md
  specs/adrs/291121-display all saved recipes.md
Labels: canvas

#185 Sort and filter interface functionality 99% complete
  source/index.html
  source/js/main.js
  source/styles/main.css
Labels: high priority

#191 clear sorting and filtering button
  source/index.html
  source/js/main.js
Labels: 3 points

#193 randomize offset for explore
  source/js/main.js
Labels: 1 point

#228 208 fix bug 0 min prep/cook time
  source/scripts/main.js
Labels: 1 point

#241 Added Issue Template for Testing
  .github/ISSUE_TEMPLATE/testing.md
Labels: house-keeping

#260 201 scaling ingredients on expanded recipe page branch2
  source/index.html
  source/scripts/main.js
  source/styles/main.css
Labels: 5 points

#263 lighthouse test screenshot
  __tests__/lighthouse_test/lighthouse_test_1.png
  __tests__/lighthouse_test/lighthouse_test_2.png
  __tests__/lighthouse_test/lighthouse_test_3.png
  __tests__/lighthouse_test/lighthouse_test_4.png
  __tests__/lighthouse_test/lighthouse_test_5.png
Labels: testing, 1 point

#268 Removed unused Measurement Type button
  source/index.html
Labels: 1 point

#259 Added duplicate sort-filter button (functional)
  source/index.html
  source/scripts/main.js
  source/styles/main.css
Labels: 1 point
